### ISSUE TITLE
https & scrolling issue

### ISSUE THREAD

**Issue by ranvirrai1987** [Strategery-Inc/Magento-InfiniteScroll#96]
Hi there,

Not a developer myself but thought i'd put this issue out there for it to be looked into. 

There seems to be an issue when using https on infinite scroll pages. What happens is that the next page doesn't load. I've singled this out to the Magento pagination which uses http for the next pages (on https page). This causes a mixed content issue, please see here: https://developer.mozilla.org/en-US/docs/Security/MixedContent . 

I think the above causes the issue but you would probably know more on this than me. Is there a solution to this?

Thanks,

Ranvir

**Comment by ranvirrai1987** [comment]
Just to add,

This issue is only likely to occur when:

1. You go to a https page such as 'my account' or 'cart' and then use search which would take you through the https handle

or

2. If you plan to use the https handle for all pages or google picks up the https handle which redirects people to https pages.

Thanks,

Ranvir

**Comment by janmyszkier** [comment]
@ranvirrai1987 this is confirmed ,the problem relies in history.replaceState used in infiniteajaxscroll library being used, I'll contact the developer to provide the fix, as I guess more people using it have this problem.

**Comment by ranvirrai1987** [comment]
Hi Janmyszkier,

That would be good, thank you. It would certainly help users of Infinite Scroll, especially if they intend to run everything through https as a means to use the new chrome browser notifications. Will bring the Magento user closer to that goal.

Thanks,

Ranvir

**Comment by janmyszkier** [comment]
try this fork:
https://github.com/janmyszkier/Magento-InfiniteScroll/tree/protocol_fix
and let me know if it works for you too, will issue pull request then

**Comment by ranvirrai1987** [comment]
Thanks for the fork. I will have to get my web developer to test this out for me but I will let you know as soon as possible.

Thanks,

Ranvir

**Comment by janmyszkier** [comment]
@ranvirrai1987 : any news from the developer?

**Comment by ranvirrai1987** [comment]
Hi @janmyszkier. Sorry for the late reply, I haven't had time to test this with the developer yet as I have been focused on the running of my store. I will try have this looked into sometime soon, but I will be in contact to let you know.

**Comment by gabrielsomoza** [comment]
@damian-pastorini could you check @janmyszkier 's fork, make sure everything works well, and if so release a new version of the extension with the fix?

**Comment by damian-pastorini** [comment]
@janmyszkier could you create a PR for this please? Thanks!

**Comment by janmyszkier** [comment]
@damian-pastorini : https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/117

**Comment by onepack** [comment]
I have an issue with the module when I make the whole frontend https.
Since then The scroll doesn't load the 2nd page anymore.
I get mixed content warnings on loading the second page.

Error: Blocked loading mixed active content "http://www.domain.com/food-supplements.html?p=2"
Source File: https://www.domain.com/food-supplements.html
Line: 5

**Comment by gabrielsomoza** [comment]
@damian-pastorini could you review the PR and merge asap so we can fix this?

**Comment by damian-pastorini** [comment]
Fixed in https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/131

**Comment by damian-pastorini** [comment]
Merged.

**Comment by damian-pastorini** [comment]
The new extension version was also uploaded to connect:
https://www.magentocommerce.com/magento-connect/strategery-infinitescroll.html

@ranvirrai1987 , @onepack you can download the fix and test.
I'm closing this issue but if you need we could re-open it.

Thanks!

**Comment by gabrielsomoza** [comment]
FYI it might take a few days until the new version is approved in Magento Connect (looks like they changed the process recently). Meanwhile you can download it from Github by going to the [releases](https://github.com/Strategery-Inc/Magento-InfiniteScroll/releases) page and getting the "Latest release" marked in green (v3.2.2 as of this writing).

**Comment by onepack** [comment]
I have installed the patched version from github. The mixed content warning is gone when scrolling down the page but... it still doesn't work. It just hangs in all browsers on the first set of products.
Cleared all cache types even reindexed to be sure but with no result.

I disabled https again for the category pages and then the module comes back to life.

**Comment by damian-pastorini** [comment]
@onepack could you give us an URL where we can take a quick look?

Some considerations you should have:
- If you have a theme installed make sure that only one jQuery instance is included.
- If you have a theme installed make sure that all the selectors are properly configured in the System / Configuration / InfiniteScroll area.
- Check the System / Configuration / Catalog / Frontend area to see the page limits are properly set to the amount of products you have.

Thanks!
